/**
 * Static seed of the Cook Out 400 debrief so the Live DB never starts empty.
 * Mirrors lib/cup-race-debrief.ts LATEST_CUP_RACE at seed time.
 */
import { type Infer } from "convex/values";
import { cupRaceDebriefValidator } from "./cupDebriefValidators";

export type SeedDebrief = Infer<typeof cupRaceDebriefValidator>;

export const SEED_RICHMOND_DEBRIEF: SeedDebrief = {
  raceName: "Cook Out 400",
  eventLabel: "Cup Series Race 24 of 36",
  track: "Richmond Raceway",
  dateLabel: "Sat · Aug 15, 2026",
  dateIso: "2026-08-15",
  tv: "USA Network",
  distance: "400 laps · 300 miles",
  winner: {
    driver: "Joey Logano",
    car: "22",
    team: "Team Penske",
    manufacturer: "Ford",
    start: 10,
    lapsLed: 95,
    margin: "0.392 sec",
    careerWin: 39,
    seasonWin: 2,
    headline: "Logano holds off Briscoe under the lights",
    blurb:
      "Started 10th, won Stage 2, then ran down Christopher Bell on fresher tires and fended off Chase Briscoe over the final five miles for his third career Richmond win — second victory in the last four starts.",
  },
  winnerPitStrategy: {
    label: "Late fresh tires over stretch",
    summary:
      "Penske stayed on the primary green-flag cycle with Briscoe all night, won Stage 2 off pit road, then took four tires on the last stop (~39 to go). Logano beat Briscoe to pit exit, erased Bell’s short-pit lead on the abrasive Richmond surface, and closed under brakes that were biting when Briscoe’s were going away.",
    totalStops: 5,
    avgStopSec: 11.42,
    bestStopSec: 10.98,
    stops: [
      {
        lap: 31,
        window: "green",
        service: "4 tires + fuel",
        durationSec: 11.55,
        posIn: "Top 10",
        posOut: "Cycle pack",
        note: "First green-flag cycle with the early wave (Larson, Cindric group). Locked onto the main rhythm instead of floating off-sequence.",
      },
      {
        lap: 70,
        window: "stage-break",
        service: "4 tires + fuel",
        durationSec: 11.40,
        posIn: "P4 stage",
        posOut: "P4",
        note: "Stage 1 break — rolled off behind Blaney / Briscoe / Cindric. Clean service kept him in the lead pack for the long Stage 2 run.",
      },
      {
        lap: 120,
        window: "green",
        service: "4 tires + fuel",
        durationSec: 11.25,
        posIn: "Lead group",
        posOut: "P2",
        note: "Mid-Stage 2 green cycle. Briscoe won the race off pit road; Logano slot second and stayed attached for the Stage 2 win run.",
      },
      {
        lap: 170,
        window: "stage-break",
        service: "4 tires + fuel + adjust",
        durationSec: 11.10,
        posIn: "P1 · Stage 2 win",
        posOut: "P1",
        decisive: false,
        note: "Stage 2 victory lap into the box — exited first over Hamlin and Briscoe. Track position carried into the final stage duel.",
      },
      {
        lap: 361,
        window: "green",
        service: "4 tires + fuel",
        durationSec: 10.98,
        posIn: "P1 (over Briscoe)",
        posOut: "P1 vs cycle · then P2 behind Bell",
        decisive: true,
        note: "Race-winning stop (~39 to go). Logano passed Briscoe on track, pitted one lap later with him/Cindric, beat Briscoe off pit road, then hunted Bell’s older tires and took the lead for good with 24 to go.",
      },
    ],
    keysToWin: [
      "Beat Briscoe off the final green-flag stop — free track position before the last restart-free run.",
      "Refused Bell’s stretch play; fresher stickers erased a ~1+ second gap in three laps of traffic.",
      "Best crew stop of the night (10.98s) landed on the key window that decided the race.",
      "Stayed sequential with the leaders instead of gambling on an early final stop.",
    ],
    note: "Winner stop chart reconstructed from published race reports (SpeedwayMedia, AP/recaps). Lap marks ±1–2; stop times editorial until NASCAR Loops Data publishes.",
  },
  stages: [
    { stage: 1, winner: "Ryan Blaney", runnerUp: "Chase Briscoe", note: "Blaney led early on pole before Briscoe closed late" },
    { stage: 2, winner: "Joey Logano", runnerUp: "Denny Hamlin", note: "Logano took the lead slicing traffic at lap 172" },
    { stage: 3, winner: "Joey Logano", runnerUp: "Chase Briscoe", note: "Final green-flag stop decided the No. 22 vs No. 19 duel" },
  ],
  stats: {
    leadChanges: 29,
    leaders: 10,
    cautions: 4,
    cautionLaps: 31,
    avgSpeed: "98.343 mph",
    pole: "Ryan Blaney",
    poleTime: "22.225",
    mostLapsLed: "Chase Briscoe",
    mostLapsLedCount: 171,
    fastestLap: "Ryan Blaney · 22.738",
  },
  finishers: [
    { pos: 1, car: "22", driver: "Joey Logano", team: "Team Penske", start: 10, status: "Running", gap: "—", lapsLed: 95 },
    { pos: 2, car: "19", driver: "Chase Briscoe", team: "Joe Gibbs Racing", start: 2, status: "Running", gap: "0.392", lapsLed: 171 },
    { pos: 3, car: "2", driver: "Austin Cindric", team: "Team Penske", start: 23, status: "Running", gap: "7.953" },
    { pos: 4, car: "11", driver: "Denny Hamlin", team: "Joe Gibbs Racing", start: 14, status: "Running", gap: "11.296" },
    { pos: 5, car: "9", driver: "Chase Elliott", team: "Hendrick Motorsports", start: 13, status: "Running", gap: "13.701" },
    { pos: 6, car: "5", driver: "Kyle Larson", team: "Hendrick Motorsports", start: 30, status: "Running", gap: "14.071" },
    { pos: 7, car: "20", driver: "Christopher Bell", team: "Joe Gibbs Racing", start: 8, status: "Running", gap: "15.178" },
    { pos: 8, car: "21", driver: "Josh Berry", team: "Wood Brothers", start: 3, status: "Running", gap: "15.904" },
    { pos: 9, car: "24", driver: "William Byron", team: "Hendrick Motorsports", start: 5, status: "Running", gap: "18.592" },
    { pos: 10, car: "48", driver: "Alex Bowman", team: "Hendrick Motorsports", start: 25, status: "Running", gap: "20.960" },
  ],
  // Editorial 4-tire averages reconstructed from broadcast timing + race notes.
  // Swap for official Loops Data when published.
  pitScoreboard: [
    { driver: "Joey Logano", car: "22", avgStop: 11.42, bestStop: 10.98, stops: 4, isWinner: true, note: "Beat Briscoe off final stop (~L362)" },
    { driver: "Austin Cindric", car: "2", avgStop: 11.71, bestStop: 11.20, stops: 4, note: "Recovered after one messy mid-race stop" },
    { driver: "Denny Hamlin", car: "11", avgStop: 11.88, bestStop: 11.35, stops: 4 },
    { driver: "Chase Briscoe", car: "19", avgStop: 12.05, bestStop: 11.40, stops: 4, note: "Lost the door on last stop to #22" },
    { driver: "Kyle Larson", car: "5", avgStop: 12.18, bestStop: 11.55, stops: 4 },
    { driver: "Christopher Bell", car: "20", avgStop: 12.24, bestStop: 11.62, stops: 3, note: "Longer/strategy stint variance" },
    { driver: "Ryan Blaney", car: "12", avgStop: 12.41, bestStop: 11.70, stops: 4 },
    { driver: "Chase Elliott", car: "9", avgStop: 13.16, bestStop: 11.85, stops: 4, note: "Slow stop mid-Stage 3 (~L279)" },
  ],
  pitNote:
    "Avg 4-tire stop times are editorial reconstruction from broadcast timing and published race notes — not official NASCAR Loops Data. Update with Loops when available.",
  incidents: [
    {
      bin: "penalty",
      lap: 38,
      driver: "Ty Gibbs",
      car: "54",
      title: "Pass-through · pit road",
      detail: "Gibbs + Austin Hill both served pass-through penalties for pit-road violations during the first green-flag cycle.",
    },
    {
      bin: "penalty",
      lap: 38,
      driver: "Austin Hill",
      car: "33",
      title: "Pass-through · pit road",
      detail: "Hill also sent to the tail for a pit-road violation in Stage 1 — ended 23rd.",
    },
    {
      bin: "wreck",
      lap: 126,
      driver: "Zane Smith",
      car: "38",
      title: "Solo spin · Turn 2 wall",
      detail: "Smith rotated on his own off Turn 2 and tagged the outside wall, bringing out a Stage 2 caution. Finished 36th, 34 laps down.",
    },
    {
      bin: "pit",
      lap: 181,
      driver: "Austin Cindric",
      car: "2",
      title: "Ugly green-flag service",
      detail: "Slow stop under green nearly clipped Daniel Suárez on pit road — costly cycle, recovered to a Penske 1-3 finish.",
    },
    {
      bin: "pit",
      lap: 279,
      driver: "Chase Elliott",
      car: "9",
      title: "Slow stop · Stage 3",
      detail: "Elliott lost multiple positions on a sluggish 4-tire stop during the stage’s first cycle; still salvaged a top-five.",
    },
    {
      bin: "mechanical",
      lap: 284,
      driver: "Carson Hocevar",
      car: "77",
      title: "Stopped on track · DNF",
      detail: "Hocevar rolled to a stop high in the groove, drawing a mid-Stage 3 yellow. Official result: 37th, 121 laps down.",
    },
    {
      bin: "pit",
      lap: 362,
      driver: "Joey Logano",
      car: "22",
      title: "Race-winning final stop",
      detail: "Logano beat Chase Briscoe to pit exit on the last green-flag stop, then ran down Bell and cracked the No. 19 over the final run.",
    },
  ],
  takeaways: [
    "Penske short-track program is hot — Logano win, Cindric P3, Blaney stage-1 win (but P13 after late-cycle trouble).",
    "Briscoe led a race-high 171 laps and still finished second — execution, not speed, cost the win.",
    "Bell’s longer Stage 3 strategy put him out front with ~28 to go, but Logano’s fresher tires erased a 3-second gap in six laps.",
    "Playoff math tightens with two regular-season races left (New Hampshire, Daytona).",
  ],
  nextRace: {
    name: "Dollar Tree 301",
    track: "New Hampshire Motor Speedway",
    when: "Sun Aug 23 · 1:00 PM MDT · USA / HBO Max",
  },
};
