export const STARTER_QUESTIONS = [
  {
    seedKey: "q01-darlington-nickname",
    prompt: "What is Darlington Raceway’s longtime nickname?",
    answers: ["The Lady in Black", "Too Tough to Tame", "The Paperclip", "The Tricky Mile"],
    correctIndex: 0,
    explain: "Fans also say Too Tough to Tame. The egg-shaped oval is infamous for the “Darlington stripe.”",
    pack: "daily" as const,
    category: "tracks" as const,
    difficulty: "easy" as const,
  },
  {
    seedKey: "q02-petty-200",
    prompt: "Who holds the Cup Series record with 200 wins?",
    answers: ["Jeff Gordon", "Richard Petty", "Dale Earnhardt", "Jimmie Johnson"],
    correctIndex: 1,
    explain: "The King won 200 times. Johnson and Petty are tied on seven championships.",
    pack: "daily" as const,
    category: "history" as const,
    difficulty: "easy" as const,
  },
  {
    seedKey: "q03-chase-16",
    prompt: "How many drivers make the 2026 Cup Chase?",
    answers: ["12", "16", "8", "10"],
    correctIndex: 1,
    explain: "The 2026 Chase is 16 drivers, 10 races, no elimination rounds.",
    pack: "daily" as const,
    category: "season2026" as const,
    difficulty: "easy" as const,
  },
  {
    seedKey: "q04-chase-start",
    prompt: "Where does the 2026 Cup Chase start?",
    answers: ["Daytona", "Darlington", "Bristol", "Homestead-Miami"],
    correctIndex: 1,
    explain: "The Southern 500 at Darlington is Chase race 1 of 10 (Sept 6, 2026).",
    pack: "daily" as const,
    category: "season2026" as const,
    difficulty: "medium" as const,
  },
  {
    seedKey: "q05-champion-crowned",
    prompt: "Where is the 2026 Cup champion crowned?",
    answers: ["Phoenix", "Homestead-Miami", "Martinsville", "Las Vegas"],
    correctIndex: 1,
    explain: "The finale is Nov 8, 2026 at Homestead. Highest 10-race total wins the Cup.",
    pack: "daily" as const,
    category: "season2026" as const,
    difficulty: "hard" as const,
  },
  {
    seedKey: "q06-superspeedways",
    prompt: "Which two tracks are the classic superspeedways?",
    answers: [
      "Daytona and Talladega",
      "Bristol and Martinsville",
      "Sonoma and Watkins Glen",
      "Iowa and Richmond",
    ],
    correctIndex: 0,
    explain: "Plate / draft racing. Everyone else is a different kind of fight.",
    pack: "daily" as const,
    category: "tracks" as const,
    difficulty: "easy" as const,
  },
  {
    seedKey: "q07-bristol-length",
    prompt: "About how long is Bristol Motor Speedway?",
    answers: ["2.5 miles", "1.5 miles", "0.533 miles", "0.75 miles"],
    correctIndex: 2,
    explain: "High-banked concrete short track. Saturday night there is a different sport.",
    pack: "daily" as const,
    category: "tracks" as const,
    difficulty: "medium" as const,
  },
  {
    seedKey: "q08-oreilly",
    prompt: "In 2026, what is the national series under Cup called?",
    answers: ["Busch Series", "Nationwide Series", "Xfinity Series", "O'Reilly Auto Parts Series"],
    correctIndex: 3,
    explain: "The second-tier national series was rebranded O'Reilly for 2026.",
    pack: "daily" as const,
    category: "oreilly" as const,
    difficulty: "easy" as const,
  },
  {
    seedKey: "q09-preece-daytona",
    prompt: "Who won the 2026 Coke Zero Sugar 400 at Daytona?",
    answers: ["Shane van Gisbergen", "Ryan Preece", "Daniel Suárez", "Denny Hamlin"],
    correctIndex: 1,
    explain: "First career Cup win, overtime, 0.024 seconds over Suárez. Locked the last Chase seed.",
    pack: "daily" as const,
    category: "cup" as const,
    difficulty: "medium" as const,
  },
  {
    seedKey: "q10-two-wins",
    prompt: "Did two wins auto-lock a 2026 Chase berth?",
    answers: ["Yes", "No", "Only if you also had a top 10 in points", "Only at Daytona"],
    correctIndex: 1,
    explain: "2026 is points-only to make the 16. SVG missed despite two wins.",
    pack: "daily" as const,
    category: "season2026" as const,
    difficulty: "hard" as const,
  },
  {
    seedKey: "q11-gwc",
    prompt: "What does a green-white-checkered finish mean?",
    answers: [
      "Qualifying format",
      "Overtime: green, one to go, then checkers",
      "Stage break",
      "Rain delay",
    ],
    correctIndex: 1,
    explain: "If the race goes overdue under caution near the end, they try to finish under green.",
    pack: "daily" as const,
    category: "beginner" as const,
    difficulty: "medium" as const,
  },
  {
    seedKey: "q12-preece-ford",
    prompt: "Which manufacturer fielded Ryan Preece’s No. 60 at Daytona 2026?",
    answers: ["Chevrolet", "Toyota", "Ford", "Dodge"],
    correctIndex: 2,
    explain: "RFK Racing Ford. Preece’s first Cup win.",
    pack: "daily" as const,
    category: "cup" as const,
    difficulty: "hard" as const,
  },
];
