export type Series2027Key = 'cup' | 'xfinity' | 'truck';

export type Race2027Kind = 'points' | 'exhibition';

export type Race2027 = {
  id: string;
  /** YYYY-MM for grouping; Watkins Glen still has no day */
  month: string;
  iso?: string;
  dateLabel: string;
  weekday?: string;
  name: string;
  track: string;
  tv: string;
  window?: string;
  kind: Race2027Kind;
  tags?: string[];
};

export type Series2027 = {
  key: Series2027Key;
  name: string;
  shortName: string;
  accentClass: string;
  barClass: string;
  note: string;
  races: Race2027[];
};

export const SCHEDULE_2027_UPDATED = 'August 25, 2026';

export const SCHEDULE_2027_SOURCE =
  'https://www.nascar.com/news-media/2026/08/10/2027-nascar-schedule-confirmed-dates-tracks-for-all-three-national-series/';

export const SCHEDULE_2027_HEADLINES = [
  'San Diego street race returns Aug. 1',
  'Bowman Gray Trucks — first national points since 1971',
  'Trucks to Canada (Mosport) Sept. 5',
  'Richmond opens the Cup Chase',
  'Southern 500 is the regular-season finale',
  'Homestead crowns all three champs',
];

export const SCHEDULE_2027_WHATS_NEW = [
  {
    title: 'Clash back at Daytona',
    body: 'The exhibition opener returns to the superspeedway on Feb. 13 (FOX). Bowman Gray is no longer the Clash host.',
  },
  {
    title: 'Race the Base, round 2',
    body: 'Cup hits Naval Base Coronado’s 3.4-mile Qualcomm Circuit on Aug. 1 (TNT Sports). O’Reilly runs July 31.',
  },
  {
    title: 'All-Star at North Wilkesboro',
    body: 'The $1 million exhibition returns to the 0.625-mile oval on May 23 (FOX). Dover goes back to a points race.',
  },
  {
    title: 'Richmond opens The Chase',
    body: 'First time since 2021. Cup on Saturday, Sept. 11 (USA). The Southern 500 (Sept. 5) is the regular-season finale.',
  },
  {
    title: 'Bowman Gray goes points',
    body: 'Craftsman Trucks race “The Madhouse” on Friday, Aug. 20 (FOX Sports) — first national-series points race there since 1971.',
  },
  {
    title: 'Trucks return to Canada',
    body: 'Canadian Tire Motorsport Park on Sunday, Sept. 5 (FOX Sports) is the Truck regular-season finale, first visit since 2019.',
  },
] as const;

export const CUP_2027: Race2027[] = [
  {
    id: 'cup-clash',
    month: '2027-02',
    iso: '2027-02-13',
    dateLabel: 'Feb 13',
    weekday: 'Sat',
    name: 'Busch Light Clash at Daytona',
    track: 'Daytona International Speedway',
    tv: 'FOX',
    window: '8:00–11:00 p.m. ET',
    kind: 'exhibition',
    tags: ['Exhibition'],
  },
  {
    id: 'cup-duel',
    month: '2027-02',
    iso: '2027-02-18',
    dateLabel: 'Feb 18',
    weekday: 'Thu',
    name: 'The Duel at Daytona',
    track: 'Daytona International Speedway',
    tv: 'FOX',
    window: '7:00–10:00 p.m. ET',
    kind: 'exhibition',
    tags: ['Exhibition', 'Qualifying races'],
  },
  {
    id: 'cup-daytona-500',
    month: '2027-02',
    iso: '2027-02-21',
    dateLabel: 'Feb 21',
    weekday: 'Sun',
    name: 'Daytona 500',
    track: 'Daytona International Speedway',
    tv: 'FOX',
    window: '2:30–7:00 p.m. ET',
    kind: 'points',
    tags: ['Crown jewel', 'Race 1'],
  },
  {
    id: 'cup-atlanta-spring',
    month: '2027-02',
    iso: '2027-02-28',
    dateLabel: 'Feb 28',
    weekday: 'Sun',
    name: 'Autotrader 400',
    track: 'EchoPark Speedway',
    tv: 'FS1',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-cota',
    month: '2027-03',
    iso: '2027-03-07',
    dateLabel: 'Mar 7',
    weekday: 'Sun',
    name: 'Circuit of The Americas',
    track: 'Circuit of The Americas',
    tv: 'FOX',
    window: '3:30–7:00 p.m. ET',
    kind: 'points',
    tags: ['Road course'],
  },
  {
    id: 'cup-phoenix-spring',
    month: '2027-03',
    iso: '2027-03-14',
    dateLabel: 'Mar 14',
    weekday: 'Sun',
    name: 'Phoenix Raceway',
    track: 'Phoenix Raceway',
    tv: 'FOX',
    window: '3:30–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-vegas-spring',
    month: '2027-03',
    iso: '2027-03-21',
    dateLabel: 'Mar 21',
    weekday: 'Sun',
    name: 'Las Vegas Motor Speedway',
    track: 'Las Vegas Motor Speedway',
    tv: 'FOX',
    window: '3:30–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-darlington-spring',
    month: '2027-04',
    iso: '2027-04-04',
    dateLabel: 'Apr 4',
    weekday: 'Sun',
    name: 'Darlington Raceway',
    track: 'Darlington Raceway',
    tv: 'FS1',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-bristol-spring',
    month: '2027-04',
    iso: '2027-04-11',
    dateLabel: 'Apr 11',
    weekday: 'Sun',
    name: 'Bristol Motor Speedway',
    track: 'Bristol Motor Speedway',
    tv: 'FOX',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Short track'],
  },
  {
    id: 'cup-martinsville-spring',
    month: '2027-04',
    iso: '2027-04-18',
    dateLabel: 'Apr 18',
    weekday: 'Sun',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'FS1',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Short track'],
  },
  {
    id: 'cup-talladega-spring',
    month: '2027-04',
    iso: '2027-04-25',
    dateLabel: 'Apr 25',
    weekday: 'Sun',
    name: 'Talladega Superspeedway',
    track: 'Talladega Superspeedway',
    tv: 'FOX',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Superspeedway'],
  },
  {
    id: 'cup-texas',
    month: '2027-05',
    iso: '2027-05-02',
    dateLabel: 'May 2',
    weekday: 'Sun',
    name: 'Texas Motor Speedway',
    track: 'Texas Motor Speedway',
    tv: 'FOX',
    window: '3:30–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-kansas-spring',
    month: '2027-05',
    iso: '2027-05-09',
    dateLabel: 'May 9',
    weekday: 'Sun',
    name: 'Kansas Speedway',
    track: 'Kansas Speedway',
    tv: 'FOX',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-dover',
    month: '2027-05',
    iso: '2027-05-16',
    dateLabel: 'May 16',
    weekday: 'Sun',
    name: 'Dover Motor Speedway',
    track: 'Dover Motor Speedway',
    tv: 'FS1',
    window: '2:00–6:00 p.m. ET',
    kind: 'points',
    tags: ['Back to points'],
  },
  {
    id: 'cup-all-star',
    month: '2027-05',
    iso: '2027-05-23',
    dateLabel: 'May 23',
    weekday: 'Sun',
    name: 'NASCAR All-Star Race',
    track: 'North Wilkesboro Speedway',
    tv: 'FOX',
    window: '8:00–11:00 p.m. ET',
    kind: 'exhibition',
    tags: ['Exhibition', 'Prime time'],
  },
  {
    id: 'cup-pocono',
    month: '2027-06',
    iso: '2027-06-13',
    dateLabel: 'Jun 13',
    weekday: 'Sun',
    name: 'Pocono Raceway',
    track: 'Pocono Raceway',
    tv: 'Prime Video',
    window: '2:00–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-chicagoland',
    month: '2027-06',
    iso: '2027-06-27',
    dateLabel: 'Jun 27',
    weekday: 'Sun',
    name: 'Chicagoland Speedway',
    track: 'Chicagoland Speedway',
    tv: 'Prime Video',
    window: '2:30–6:30 p.m. ET',
    kind: 'points',
    tags: ['Prime’s last 2027 race'],
  },
  {
    id: 'cup-iowa',
    month: '2027-07',
    iso: '2027-07-04',
    dateLabel: 'Jul 4',
    weekday: 'Sun',
    name: 'Iowa Speedway',
    track: 'Iowa Speedway',
    tv: 'TNT Sports',
    window: '7:00–11:00 p.m. ET',
    kind: 'points',
    tags: ['July 4'],
  },
  {
    id: 'cup-atlanta-summer',
    month: '2027-07',
    iso: '2027-07-18',
    dateLabel: 'Jul 18',
    weekday: 'Sun',
    name: 'EchoPark Speedway',
    track: 'EchoPark Speedway',
    tv: 'TNT Sports',
    window: '7:00–11:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'cup-coronado',
    month: '2027-08',
    iso: '2027-08-01',
    dateLabel: 'Aug 1',
    weekday: 'Sun',
    name: 'Naval Base Coronado',
    track: 'Qualcomm Circuit at Naval Base Coronado',
    tv: 'TNT Sports',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Street course', 'San Diego'],
  },
  {
    id: 'cup-bristol-night',
    month: '2027-08',
    iso: '2027-08-14',
    dateLabel: 'Aug 14',
    weekday: 'Sat',
    name: 'Bass Pro Shops Night Race',
    track: 'Bristol Motor Speedway',
    tv: 'TNT Sports',
    window: '7:30–11:30 p.m. ET',
    kind: 'points',
    tags: ['Night race'],
  },
  {
    id: 'cup-gateway',
    month: '2027-08',
    iso: '2027-08-22',
    dateLabel: 'Aug 22',
    weekday: 'Sun',
    name: 'Enjoy Illinois 300',
    track: 'World Wide Technology Raceway',
    tv: 'USA Network',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Moved out of Chase'],
  },
  {
    id: 'cup-daytona-summer',
    month: '2027-08',
    iso: '2027-08-28',
    dateLabel: 'Aug 28',
    weekday: 'Sat',
    name: 'Daytona International Speedway',
    track: 'Daytona International Speedway',
    tv: 'USA Network',
    window: '7:30–11:30 p.m. ET',
    kind: 'points',
    tags: ['Superspeedway'],
  },
  {
    id: 'cup-southern-500',
    month: '2027-09',
    iso: '2027-09-05',
    dateLabel: 'Sep 5',
    weekday: 'Sun',
    name: 'Southern 500',
    track: 'Darlington Raceway',
    tv: 'USA Network',
    window: '6:00–10:00 p.m. ET',
    kind: 'points',
    tags: ['Crown jewel', 'Regular-season finale'],
  },
  {
    id: 'cup-richmond-chase',
    month: '2027-09',
    iso: '2027-09-11',
    dateLabel: 'Sep 11',
    weekday: 'Sat',
    name: 'Richmond Raceway',
    track: 'Richmond Raceway',
    tv: 'USA Network',
    window: '7:30–11:30 p.m. ET',
    kind: 'points',
    tags: ['Chase opener'],
  },
  {
    id: 'cup-watkins-glen',
    month: '2027-09',
    dateLabel: 'TBD',
    name: 'Watkins Glen International',
    track: 'Watkins Glen International',
    tv: 'USA Network',
    kind: 'points',
    tags: ['Date TBA', 'Road course'],
  },
  {
    id: 'cup-loudon',
    month: '2027-09',
    iso: '2027-09-26',
    dateLabel: 'Sep 26',
    weekday: 'Sun',
    name: 'New Hampshire Motor Speedway',
    track: 'New Hampshire Motor Speedway',
    tv: 'USA Network',
    window: '2:00–6:00 p.m. ET',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'cup-kansas-chase',
    month: '2027-10',
    iso: '2027-10-03',
    dateLabel: 'Oct 3',
    weekday: 'Sun',
    name: 'Kansas Speedway',
    track: 'Kansas Speedway',
    tv: 'USA Network',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'cup-vegas-chase',
    month: '2027-10',
    iso: '2027-10-10',
    dateLabel: 'Oct 10',
    weekday: 'Sun',
    name: 'Las Vegas Motor Speedway',
    track: 'Las Vegas Motor Speedway',
    tv: 'USA Network',
    window: '2:30–6:30 p.m. ET',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'cup-phoenix-chase',
    month: '2027-10',
    iso: '2027-10-24',
    dateLabel: 'Oct 24',
    weekday: 'Sun',
    name: 'Phoenix Raceway',
    track: 'Phoenix Raceway',
    tv: 'USA Network',
    window: '2:30–6:30 p.m. ET',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'cup-talladega-chase',
    month: '2027-10',
    iso: '2027-10-31',
    dateLabel: 'Oct 31',
    weekday: 'Sun',
    name: 'Talladega Superspeedway',
    track: 'Talladega Superspeedway',
    tv: 'USA Network',
    window: '2:00–6:00 p.m. ET',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'cup-martinsville-chase',
    month: '2027-11',
    iso: '2027-11-07',
    dateLabel: 'Nov 7',
    weekday: 'Sun',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'USA Network',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Penultimate'],
  },
  {
    id: 'cup-homestead',
    month: '2027-11',
    iso: '2027-11-14',
    dateLabel: 'Nov 14',
    weekday: 'Sun',
    name: 'Championship Race',
    track: 'Homestead-Miami Speedway',
    tv: 'USA Network',
    window: '3:00–7:00 p.m. ET',
    kind: 'points',
    tags: ['Championship'],
  },
];

export const XFINITY_2027: Race2027[] = [
  {
    id: 'x-daytona',
    month: '2027-02',
    iso: '2027-02-20',
    dateLabel: 'Feb 20',
    weekday: 'Sat',
    name: 'Daytona International Speedway',
    track: 'Daytona International Speedway',
    tv: 'The CW',
    window: '2:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-atlanta-spring',
    month: '2027-02',
    iso: '2027-02-27',
    dateLabel: 'Feb 27',
    weekday: 'Sat',
    name: 'EchoPark Speedway',
    track: 'EchoPark Speedway',
    tv: 'The CW',
    window: '4:30–8:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-cota',
    month: '2027-03',
    iso: '2027-03-06',
    dateLabel: 'Mar 6',
    weekday: 'Sat',
    name: 'Circuit of The Americas',
    track: 'Circuit of The Americas',
    tv: 'The CW',
    window: '2:30–6:00 p.m. ET',
    kind: 'points',
    tags: ['Road course'],
  },
  {
    id: 'x-phoenix',
    month: '2027-03',
    iso: '2027-03-13',
    dateLabel: 'Mar 13',
    weekday: 'Sat',
    name: 'Phoenix Raceway',
    track: 'Phoenix Raceway',
    tv: 'The CW',
    window: '5:00–8:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-vegas-spring',
    month: '2027-03',
    iso: '2027-03-20',
    dateLabel: 'Mar 20',
    weekday: 'Sat',
    name: 'Las Vegas Motor Speedway',
    track: 'Las Vegas Motor Speedway',
    tv: 'The CW',
    window: '4:30–8:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-darlington-spring',
    month: '2027-04',
    iso: '2027-04-03',
    dateLabel: 'Apr 3',
    weekday: 'Sat',
    name: 'Darlington Raceway',
    track: 'Darlington Raceway',
    tv: 'The CW',
    window: '3:00–6:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-bristol',
    month: '2027-04',
    iso: '2027-04-10',
    dateLabel: 'Apr 10',
    weekday: 'Sat',
    name: 'Bristol Motor Speedway',
    track: 'Bristol Motor Speedway',
    tv: 'The CW',
    window: '4:00–7:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-martinsville-spring',
    month: '2027-04',
    iso: '2027-04-17',
    dateLabel: 'Apr 17',
    weekday: 'Sat',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'The CW',
    window: '1:00–4:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-talladega',
    month: '2027-04',
    iso: '2027-04-24',
    dateLabel: 'Apr 24',
    weekday: 'Sat',
    name: 'Talladega Superspeedway',
    track: 'Talladega Superspeedway',
    tv: 'The CW',
    window: '2:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-texas',
    month: '2027-05',
    iso: '2027-05-01',
    dateLabel: 'May 1',
    weekday: 'Sat',
    name: 'Texas Motor Speedway',
    track: 'Texas Motor Speedway',
    tv: 'The CW',
    window: '2:00–5:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-dover',
    month: '2027-05',
    iso: '2027-05-15',
    dateLabel: 'May 15',
    weekday: 'Sat',
    name: 'Dover Motor Speedway',
    track: 'Dover Motor Speedway',
    tv: 'The CW',
    window: '3:00–6:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-nws',
    month: '2027-05',
    iso: '2027-05-22',
    dateLabel: 'May 22',
    weekday: 'Sat',
    name: 'North Wilkesboro Speedway',
    track: 'North Wilkesboro Speedway',
    tv: 'The CW',
    window: '2:00–5:00 p.m. ET',
    kind: 'points',
    tags: ['First visit since 1985'],
  },
  {
    id: 'x-nashville',
    month: '2027-06',
    iso: '2027-06-05',
    dateLabel: 'Jun 5',
    weekday: 'Sat',
    name: 'Nashville Super Speedway',
    track: 'Nashville Super Speedway',
    tv: 'The CW',
    window: '3:00–6:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 'x-pocono',
    month: '2027-06',
    iso: '2027-06-12',
    dateLabel: 'Jun 12',
    weekday: 'Sat',
    name: 'Pocono Raceway',
    track: 'Pocono Raceway',
    tv: 'The CW',
    kind: 'points',
  },
  {
    id: 'x-chicagoland',
    month: '2027-06',
    iso: '2027-06-26',
    dateLabel: 'Jun 26',
    weekday: 'Sat',
    name: 'Chicagoland Speedway',
    track: 'Chicagoland Speedway',
    tv: 'The CW',
    kind: 'points',
  },
  {
    id: 'x-iowa',
    month: '2027-07',
    iso: '2027-07-03',
    dateLabel: 'Jul 3',
    weekday: 'Sat',
    name: 'Iowa Speedway',
    track: 'Iowa Speedway',
    tv: 'The CW',
    kind: 'points',
  },
  {
    id: 'x-mexico',
    month: '2027-07',
    iso: '2027-07-10',
    dateLabel: 'Jul 10',
    weekday: 'Sat',
    name: 'Autódromo Hermanos Rodríguez',
    track: 'Autódromo Hermanos Rodríguez',
    tv: 'The CW',
    kind: 'points',
    tags: ['Mexico City', 'Road course'],
  },
  {
    id: 'x-atlanta-summer',
    month: '2027-07',
    iso: '2027-07-17',
    dateLabel: 'Jul 17',
    weekday: 'Sat',
    name: 'EchoPark Speedway',
    track: 'EchoPark Speedway',
    tv: 'The CW',
    kind: 'points',
  },
  {
    id: 'x-coronado',
    month: '2027-07',
    iso: '2027-07-31',
    dateLabel: 'Jul 31',
    weekday: 'Sat',
    name: 'Naval Base Coronado',
    track: 'Qualcomm Circuit at Naval Base Coronado',
    tv: 'The CW',
    kind: 'points',
    tags: ['Street course'],
  },
  {
    id: 'x-gateway',
    month: '2027-08',
    iso: '2027-08-21',
    dateLabel: 'Aug 21',
    weekday: 'Sat',
    name: 'Nu Way 225',
    track: 'World Wide Technology Raceway',
    tv: 'The CW',
    kind: 'points',
  },
  {
    id: 'x-darlington-finale',
    month: '2027-09',
    iso: '2027-09-04',
    dateLabel: 'Sep 4',
    weekday: 'Sat',
    name: 'Darlington Raceway',
    track: 'Darlington Raceway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Regular-season finale'],
  },
  {
    id: 'x-richmond-chase',
    month: '2027-09',
    iso: '2027-09-10',
    dateLabel: 'Sep 10',
    weekday: 'Fri',
    name: 'Richmond Raceway',
    track: 'Richmond Raceway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Chase opener', 'Returns after two-year hiatus'],
  },
  {
    id: 'x-kansas-chase',
    month: '2027-10',
    iso: '2027-10-02',
    dateLabel: 'Oct 2',
    weekday: 'Sat',
    name: 'Kansas Speedway',
    track: 'Kansas Speedway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'x-vegas-chase',
    month: '2027-10',
    iso: '2027-10-09',
    dateLabel: 'Oct 9',
    weekday: 'Sat',
    name: 'Las Vegas Motor Speedway',
    track: 'Las Vegas Motor Speedway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 'x-martinsville-chase',
    month: '2027-11',
    iso: '2027-11-06',
    dateLabel: 'Nov 6',
    weekday: 'Sat',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Penultimate'],
  },
  {
    id: 'x-homestead',
    month: '2027-11',
    iso: '2027-11-13',
    dateLabel: 'Nov 13',
    weekday: 'Sat',
    name: 'Championship Race',
    track: 'Homestead-Miami Speedway',
    tv: 'The CW',
    kind: 'points',
    tags: ['Championship'],
  },
];

export const TRUCK_2027: Race2027[] = [
  {
    id: 't-daytona',
    month: '2027-02',
    iso: '2027-02-12',
    dateLabel: 'Feb 12',
    weekday: 'Fri',
    name: 'Daytona International Speedway',
    track: 'Daytona International Speedway',
    tv: 'FOX Sports',
    window: '1:30–10:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-phoenix',
    month: '2027-03',
    iso: '2027-03-12',
    dateLabel: 'Mar 12',
    weekday: 'Fri',
    name: 'Phoenix Raceway',
    track: 'Phoenix Raceway',
    tv: 'FOX Sports',
    window: '3:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-rockingham',
    month: '2027-03',
    iso: '2027-03-27',
    dateLabel: 'Mar 27',
    weekday: 'Sat',
    name: 'Rockingham Speedway',
    track: 'Rockingham Speedway',
    tv: 'FOX Sports',
    window: '1:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-darlington',
    month: '2027-04',
    iso: '2027-04-02',
    dateLabel: 'Apr 2',
    weekday: 'Fri',
    name: 'Darlington Raceway',
    track: 'Darlington Raceway',
    tv: 'FOX Sports',
    window: '5:30–8:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-bristol',
    month: '2027-04',
    iso: '2027-04-09',
    dateLabel: 'Apr 9',
    weekday: 'Fri',
    name: 'Bristol Motor Speedway',
    track: 'Bristol Motor Speedway',
    tv: 'FOX Sports',
    window: '2:00–9:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-talladega-spring',
    month: '2027-04',
    iso: '2027-04-23',
    dateLabel: 'Apr 23',
    weekday: 'Fri',
    name: 'Talladega Superspeedway',
    track: 'Talladega Superspeedway',
    tv: 'FOX Sports',
    window: '1:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-kansas-spring',
    month: '2027-05',
    iso: '2027-05-08',
    dateLabel: 'May 8',
    weekday: 'Sat',
    name: 'Kansas Speedway',
    track: 'Kansas Speedway',
    tv: 'FOX Sports',
    window: '1:30–6:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-dover',
    month: '2027-05',
    iso: '2027-05-14',
    dateLabel: 'May 14',
    weekday: 'Fri',
    name: 'Dover Motor Speedway',
    track: 'Dover Motor Speedway',
    tv: 'FOX Sports',
    window: '7:00–9:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-nws',
    month: '2027-05',
    iso: '2027-05-21',
    dateLabel: 'May 21',
    weekday: 'Fri',
    name: 'North Wilkesboro Speedway',
    track: 'North Wilkesboro Speedway',
    tv: 'FOX Sports',
    window: '8:00–10:00 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-charlotte',
    month: '2027-05',
    iso: '2027-05-29',
    dateLabel: 'May 29',
    weekday: 'Sat',
    name: 'Charlotte Motor Speedway',
    track: 'Charlotte Motor Speedway',
    tv: 'FOX Sports',
    window: '1:30–3:30 p.m. ET',
    kind: 'points',
  },
  {
    id: 't-nashville',
    month: '2027-06',
    iso: '2027-06-04',
    dateLabel: 'Jun 4',
    weekday: 'Fri',
    name: 'Nashville Super Speedway',
    track: 'Nashville Super Speedway',
    tv: 'FOX Sports',
    kind: 'points',
  },
  {
    id: 't-pocono',
    month: '2027-06',
    iso: '2027-06-11',
    dateLabel: 'Jun 11',
    weekday: 'Fri',
    name: 'Pocono Raceway',
    track: 'Pocono Raceway',
    tv: 'FOX Sports',
    kind: 'points',
  },
  {
    id: 't-lime-rock',
    month: '2027-07',
    iso: '2027-07-09',
    dateLabel: 'Jul 9',
    weekday: 'Fri',
    name: 'Lime Rock Park',
    track: 'Lime Rock Park',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Road course'],
  },
  {
    id: 't-atlanta',
    month: '2027-07',
    iso: '2027-07-16',
    dateLabel: 'Jul 16',
    weekday: 'Fri',
    name: 'EchoPark Speedway',
    track: 'EchoPark Speedway',
    tv: 'FOX Sports',
    kind: 'points',
  },
  {
    id: 't-bowman-gray',
    month: '2027-08',
    iso: '2027-08-20',
    dateLabel: 'Aug 20',
    weekday: 'Fri',
    name: 'Bowman Gray Stadium',
    track: 'Bowman Gray Stadium',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['First national points since 1971', 'Quarter-mile'],
  },
  {
    id: 't-mosport',
    month: '2027-09',
    iso: '2027-09-05',
    dateLabel: 'Sep 5',
    weekday: 'Sun',
    name: 'Canadian Tire Motorsport Park',
    track: 'Canadian Tire Motorsport Park',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Canada', 'Regular-season finale', 'Road course'],
  },
  {
    id: 't-kansas-chase',
    month: '2027-10',
    iso: '2027-10-01',
    dateLabel: 'Oct 1',
    weekday: 'Fri',
    name: 'Kansas Speedway',
    track: 'Kansas Speedway',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 't-talladega-chase',
    month: '2027-10',
    iso: '2027-10-16',
    dateLabel: 'Oct 16',
    weekday: 'Sat',
    name: 'Talladega Superspeedway',
    track: 'Talladega Superspeedway',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 't-martinsville-oct',
    month: '2027-10',
    iso: '2027-10-30',
    dateLabel: 'Oct 30',
    weekday: 'Sat',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Chase'],
  },
  {
    id: 't-martinsville-nov',
    month: '2027-11',
    iso: '2027-11-05',
    dateLabel: 'Nov 5',
    weekday: 'Fri',
    name: 'Martinsville Speedway',
    track: 'Martinsville Speedway',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Penultimate'],
  },
  {
    id: 't-homestead',
    month: '2027-11',
    iso: '2027-11-12',
    dateLabel: 'Nov 12',
    weekday: 'Fri',
    name: 'Championship Race',
    track: 'Homestead-Miami Speedway',
    tv: 'FOX Sports',
    kind: 'points',
    tags: ['Championship'],
  },
];

export const SERIES_2027: Series2027[] = [
  {
    key: 'cup',
    name: 'NASCAR Cup Series',
    shortName: 'Cup',
    accentClass: 'text-series-cup',
    barClass: 'bg-series-cup',
    note: '36-race points season, still filling. Watkins Glen date TBD. Clash, Duel, and All-Star are exhibitions.',
    races: CUP_2027,
  },
  {
    key: 'xfinity',
    name: "NASCAR O'Reilly Auto Parts Series",
    shortName: "O'Reilly",
    accentClass: 'text-series-xfinity',
    barClass: 'bg-series-xfinity',
    note: 'Confirmed weekends only. North Wilkesboro returns (first since 1985). Richmond is the Chase opener after a two-year hiatus.',
    races: XFINITY_2027,
  },
  {
    key: 'truck',
    name: 'NASCAR Craftsman Truck Series',
    shortName: 'Trucks',
    accentClass: 'text-series-truck',
    barClass: 'bg-series-truck',
    note: 'Bowman Gray (Aug. 20) is the first national-series points race there since 1971. Mosport (Sept. 5) is the regular-season finale.',
    races: TRUCK_2027,
  },
];

const MONTH_NAMES: Record<string, string> = {
  '2027-02': 'February',
  '2027-03': 'March',
  '2027-04': 'April',
  '2027-05': 'May',
  '2027-06': 'June',
  '2027-07': 'July',
  '2027-08': 'August',
  '2027-09': 'September',
  '2027-10': 'October',
  '2027-11': 'November',
};

export function monthLabel(month: string): string {
  return MONTH_NAMES[month] ?? month;
}

export function countPoints(races: Race2027[]): number {
  return races.filter((race) => race.kind === 'points').length;
}

export function groupRacesByMonth(
  races: Race2027[],
): { month: string; label: string; races: Race2027[] }[] {
  const order: string[] = [];
  const groups = new Map<string, Race2027[]>();

  for (const race of races) {
    if (!groups.has(race.month)) {
      groups.set(race.month, []);
      order.push(race.month);
    }
    groups.get(race.month)!.push(race);
  }

  return order.map((month) => ({
    month,
    label: monthLabel(month),
    races: groups.get(month)!,
  }));
}
